import scala.io.Source

object app {
  def main(args: Array[String]): Unit = {

    // Create test source code for lexer
    val source = Source.fromString("LABEL loop PRINT \"hello world\" GOTO #this is comment\n 123.23132 +->= == !")
    val lexer = Lexer(source.buffered)

    // Print tokens generated by lexer
    def printLexer(lexer: Lexer): Unit = {
      val token = lexer.getToken
      if (token.tokType != TokenType.EOF)
        println(token)
        printLexer(lexer)
    }

    printLexer(lexer)
  }
}
